Update python-workflow.yml

diff --git a/.github/workflows/python-workflow.yml b/.github/workflows/python-workflow.yml
--- a/.github/workflows/python-workflow.yml
+++ b/.github/workflows/python-workflow.yml
@@ -1,18 +1,26 @@
 name: CI
 
 on:
-  push:  
+  push:
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Checkout code
+      uses: actions/checkout@v4   # This step pulls the code from your repository.
+
     - name: Set up Python 3.11
       uses: actions/setup-python@v5
       with:
-        python-version: 3.11
+        python-version: '3.11'
 
     - name: Install dependencies
       run: |
-        pip install -r requirements.txt
+        if [ -f requirements.txt ]; then
+          pip install -r requirements.txt
+        else
+          echo "requirements.txt not found!"
+          exit 1
+        fi
